package cc.essence.core.render.skia

import cc.essence.core.render.nanovg.NVG

enum class Alignment(val alignment: Int) {
    LEFT_TOP(NVG.NVG_ALIGN_LEFT or NVG.NVG_ALIGN_TOP),
    CENTER_TOP(NVG.NVG_ALIGN_CENTER or NVG.NVG_ALIGN_TOP),
    RIGHT_TOP(NVG.NVG_ALIGN_RIGHT or NVG.NVG_ALIGN_TOP),
    LEFT_MIDDLE(NVG.NVG_ALIGN_LEFT or NVG.NVG_ALIGN_MIDDLE),
    CENTER_MIDDLE(NVG.NVG_ALIGN_CENTER or NVG.NVG_ALIGN_MIDDLE),
    RIGHT_MIDDLE(NVG.NVG_ALIGN_RIGHT or NVG.NVG_ALIGN_MIDDLE),
    LEFT_BOTTOM(NVG.NVG_ALIGN_LEFT or NVG.NVG_ALIGN_BOTTOM),
    CENTER_BOTTOM(NVG.NVG_ALIGN_CENTER or NVG.NVG_ALIGN_BOTTOM),
    RIGHT_BOTTOM(NVG.NVG_ALIGN_RIGHT or NVG.NVG_ALIGN_BOTTOM)
}